import "server-only";
const ORIZON_API_KEY = process.env.ORIZON_VISA_API_KEY || "";
const ORIZON_BASE = "https://api.orizonvisa.com/v1";
export interface VisaRequirement {
  destinationCountry: string; destinationCountryName: string;
  passportCountry: string; passportCountryName: string;
  visaRequired: boolean; visaType: "visa-free" | "visa-on-arrival" | "e-visa" | "embassy-visa" | "required";
  maxStayDays?: number; processingTime?: string; fee?: string; notes?: string; eVisaUrl?: string;
}
const GCC = ["SA","AE","QA","KW","BH","OM"];
type VisaInfo = { type: VisaRequirement["visaType"]; days?: number; notes?: string };
function build(exempt: string[], arrival: string[], evisa: string[]): Record<string, VisaInfo> {
  const m: Record<string, VisaInfo> = {};
  exempt.forEach(c => m[c] = { type: "visa-free", days: 90 });
  arrival.forEach(c => m[c] = { type: "visa-on-arrival", days: 30 });
  evisa.forEach(c => m[c] = { type: "e-visa", days: 30 });
  return m;
}
const DB: Record<string, Record<string, VisaInfo>> = {
  SA: build(["AE","QA","KW","BH","OM","TR","MY","ID","TH","MV","JO","EG","GE","KZ","MA","TN","ZA","BR","KR","SG","HK","PH","VN"],["LB","KG","AL"],["IN","LK","UA","AZ","AM","MD","RU"]),
  EG: build(["AE","QA","KW","BH","OM","SA","JO","SY","LY","SD","YE","PS","MA","TN","DZ","MR","KM","DJ","GA","GN","ML","BF","BJ","CI","NE","TG","MZ"],["TR","MV","NI","TL","SB","VU"],["IN","LK","KE","TZ","UG","ZM","ZW"]),
  AE: build(["SA","QA","KW","BH","OM","EG","JO","TR","MY","ID","TH","MV","SG","HK","PH","VN","KR","JP","GB","IE","DE","FR","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","CA","US","MX","BR","AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN","SC","MU","ZA","NZ","AU","FJ","WS","TO","KZ","KG","GE","AM","AZ","MD","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","LA","KH","MM","BN","TL","TW","MO","BD","LK","MV","BT","NP"],["LB"],[]),
  US: build(["GB","IE","FR","DE","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","CA","MX","BR","AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN","SC","MU","ZA","NZ","AU","FJ","WS","TO","JP","KR","SG","HK","TW","MY","TH","PH","VN","ID","BN","TL","KZ","KG","GE","AM","AZ","MD","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","LA","KH","MM","MO","BD","LK","MV","BT","NP","AE","QA","KW","BH","OM","SA","IL","EG","MA","TN","DZ","JO","TR"],["TL","SB","VU"],["IN","CN","PK","NG","KE","TZ","UG","ZM","ZW","GH","CM","SN","ET"]),
  GB: build(["IE","FR","DE","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","CA","US","MX","BR","AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN","SC","MU","ZA","NZ","AU","FJ","WS","TO","JP","KR","SG","HK","TW","MY","TH","PH","VN","ID","BN","TL","KZ","KG","GE","AM","AZ","MD","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","LA","KH","MM","MO","BD","LK","MV","BT","NP","AE","QA","KW","BH","OM","SA","IL","EG","MA","TN","DZ","JO","TR"],["TL","SB","VU"],["IN","CN","PK","NG","KE","TZ","UG","ZM","ZW","GH","CM","SN","ET"]),
  CN: build(["AE","QA","KW","BH","OM","SA","GE","AM","AZ","MD","RU","BY","ME","RS","AL","BA","MK","XK","MN","LA","KH","MM","BN","TL","SG","TH","MY","ID","PH","VN","KZ","KG","FJ","WS","TO","SB","VU","MU","SC","EG","MA","TN"],["BD","LK","MV","NP","TL"],["IN","TR","JO"]),
  JP: build(["AE","QA","KW","BH","OM","SA","EG","JO","TR","MY","ID","TH","MV","SG","HK","PH","VN","KR","TW","MO","BN","TL","GB","IE","DE","FR","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","CA","US","MX","BR","AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN","SC","MU","ZA","NZ","AU","FJ","WS","TO","KZ","KG","GE","AM","AZ","MD","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","LA","KH","MM","BD","LK","BT","NP"],["TL","SB","VU"],["IN","CN","PK"]),
  FR: build(["GB","IE","DE","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","CA","US","MX","BR","AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN","SC","MU","ZA","NZ","AU","FJ","WS","TO","JP","KR","SG","HK","TW","MY","TH","PH","VN","ID","BN","TL","KZ","KG","GE","AM","AZ","MD","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","LA","KH","MM","MO","BD","LK","MV","BT","NP","AE","QA","KW","BH","OM","SA","IL","EG","MA","TN","DZ","JO","TR"],["TL","SB","VU"],["IN","CN","PK","NG","ET"]),
  DE: build(["GB","IE","FR","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","CA","US","MX","BR","AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN","SC","MU","ZA","NZ","AU","FJ","WS","TO","JP","KR","SG","HK","TW","MY","TH","PH","VN","ID","BN","TL","KZ","KG","GE","AM","AZ","MD","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","LA","KH","MM","MO","BD","LK","MV","BT","NP","AE","QA","KW","BH","OM","SA","IL","EG","MA","TN","DZ","JO","TR"],["TL","SB","VU"],["IN","CN","PK","NG","ET"]),
  IN: build(["NP","BT","MV","MU","SC","FJ","WS","TO","SB","VU","TL","KZ","KG","TH","SG","MY","ID","PH","VN","BN"],["TL","SB","VU","JO","LB"],["TR","AE","QA","KW","BH","OM","SA","EG","MA","TN","DZ","LK","BD","ZA","KE","TZ","UG","NG","GH","ET"]),
  NG: build(["GH","BJ","TG","CI","GN","SL","LR","ML","BF","NE","SN","GM","CV","MR","KM","DJ","GA","ST","TD","CF","CG","CD","AO","ZM","ZW","MZ","MW","BW","LS","SZ","ZA","KE","TZ","UG","RW","BI","ER"],[],["TR","AE","QA","EG","IN","CN","US","GB"]),
  BR: build(["AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN","SC","MU","ZA","NZ","AU","FJ","WS","TO","GB","IE","FR","DE","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","JP","KR","SG","HK","TW","MY","TH","PH","VN","ID","BN","TL","AE","QA","KW","BH","OM","SA","EG","MA","TN","DZ","JO","TR","KZ","KG","GE","AM","AZ","MD"],["TL","SB","VU"],["IN","CN","US","CA"]),
  RU: build(["AM","AZ","BY","KG","KZ","MD","TJ","TM","UZ","UA","MN","MK","RS","ME","BA","AL","XK","HR","CU","NI","TH","VN","MY","LA","MO","HK","KR","SG","PH","BR","AR","CL","CO","EC","PE","UY","PY","BO","VE","CR","PA","BZ","GT","HN","SV","DO","HT","ZA","EG","MA","TN","DZ","JO","TR","AE","QA","KW","BH","OM","SA","FJ","WS","TO","SB","VU","TL","MU","SC"],["BD","LK","MV","NP"],["IN","CN","PK"]),
  TR: build(["AE","QA","KW","BH","OM","SA","EG","JO","MY","ID","TH","MV","SG","HK","PH","VN","KR","JP","TW","MO","BN","TL","GB","IE","DE","FR","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","CA","US","MX","BR","AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN","SC","MU","ZA","NZ","AU","FJ","WS","TO","KZ","KG","GE","AM","AZ","MD","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","LA","KH","MM","BD","LK","BT","NP"],["LB","NP"],["IN","CN","PK","NG"]),
  PK: build(["AF","BN","KH","MV","NP","TL","TO","WS","SB","VU","TJ","TM","UZ","KG","KZ","MN"],["BD","LK","MV"],["TR","AE","QA","SA","EG","MY","ID","TH","SG"]),
  ZA: build(["BW","LS","SZ","MZ","MW","ZM","ZW","TZ","KE","UG","RW","BI","ER","AO","GH","NG","GM","SL","LR","TD","CF","CG","CD","ST","KM","DJ","GA","MR","NE","ML","BF","BJ","CI","SN","CV","EG","MA","TN","DZ","LY","SD","YE","OM","AE","QA","KW","BH","SA","JO","SY","PS","TR","GB","IE","FR","DE","IT","ES","NL","BE","AT","CH","SE","NO","DK","FI","IS","PT","GR","PL","CZ","HU","RO","BG","HR","SK","SI","EE","LV","LT","RU","UA","BY","ME","RS","AL","BA","MK","XK","MN","JP","KR","SG","HK","TW","MY","TH","PH","VN","ID","BN","TL","NZ","AU","FJ","WS","TO","SB","VU","MU","SC","BR","AR","CL","CO","PE","EC","UY","PY","BO","VE","CR","PA","BZ","GT","HN","NI","SV","DO","HT","JM","TT","BB","BS","GD","LC","VC","AG","DM","KN"],[],["IN","CN","US","CA"]),
};

export async function checkVisaRequirement(passport: string, dest: string): Promise<VisaRequirement> {
  if (ORIZON_API_KEY) { try { const r = await fetch(`${ORIZON_BASE}/visa-requirements?passport=${passport}&destination=${dest}`, { headers: { Authorization: `Bearer ${ORIZON_API_KEY}` }, signal: AbortSignal.timeout(10000) }); if (r.ok) return await r.json(); } catch {} }
  if (passport === dest) return { destinationCountry: dest, destinationCountryName: dest, passportCountry: passport, passportCountryName: passport, visaRequired: false, visaType: "visa-free", notes: "Same country" };
  if (GCC.includes(passport) && GCC.includes(dest)) return { destinationCountry: dest, destinationCountryName: dest, passportCountry: passport, passportCountryName: passport, visaRequired: false, visaType: "visa-free", maxStayDays: 90, notes: "GCC free movement" };
  const pd = DB[passport]; if (pd && pd[dest]) { const i = pd[dest]; return { destinationCountry: dest, destinationCountryName: dest, passportCountry: passport, passportCountryName: passport, visaRequired: i.type !== "visa-free", visaType: i.type, maxStayDays: i.days, processingTime: i.type === "e-visa" ? "3-5 days" : i.type === "embassy-visa" ? "5-15 days" : undefined, fee: i.type === "e-visa" ? "$40-80" : i.type === "embassy-visa" ? "$60-150" : i.type === "visa-on-arrival" ? "$30-50" : undefined, notes: i.notes }; }
  return { destinationCountry: dest, destinationCountryName: dest, passportCountry: passport, passportCountryName: passport, visaRequired: true, visaType: "embassy-visa", processingTime: "5-15 business days", fee: "$60-150", notes: "Contact the nearest embassy for visa requirements." };
}
