/**
 * CIRKLE Brain AI — Shared Context Object Schema
 * ============================================================================
 *
 * Phase 4.5 — Shared Cognitive Foundation
 *
 * This module defines the **Shared Context Object** — the single source of
 * truth that flows through every intelligence phase during a cognitive request
 * lifecycle.
 *
 * Constitutional role (Volume 0, Ch.4 §4.6):
 *   - Every phase operates on the Shared Context Object.
 *   - Each phase ENRICHES its own section only.
 *   - No phase overwrites another phase's contribution.
 *   - Context is append-only within a request lifecycle.
 *   - Provenance is preserved for every field.
 *
 * This file defines ONLY the schema and types. The lifecycle (create, enrich,
 * validate, freeze, clone, serialize, trace) is owned by the Context Manager
 * (see `context-manager.ts`).
 *
 * Design principles:
 *   - Extensible: future sections (UOB/Execution/Learning) are reserved and
 *     can be populated without breaking earlier phases.
 *   - Immutable: the Context Manager never mutates a context in place; every
 *     enrich returns a new versioned snapshot.
 *   - Provenance-first: every section carries who added it, when, and why.
 *   - Ownership-enforced: each section has exactly one constitutional owner.
 *
 * This module is pure types + a schema validator. It is NOT intelligent — it
 * never reasons, never stores long-term memory, never recommends.
 * ============================================================================
 */

// ── Section Ownership ────────────────────────────────────────────────────
//
// Each context section has exactly ONE constitutional owner. The Context
// Manager enforces that only the owner may enrich its section. This is the
// constitutional "Single Ownership" principle (Ch.2 §2.6) applied to context.

export type ContextSectionOwner =
  | "system" // request + session + metadata (Context Manager itself)
  | "gcie" // Geographic Context (Phase 1)
  | "pmb" // User Context (Phase 2)
  | "crie" // Reasoning Context (Phase 3)
  | "cross-eval" // Validation Context (shared service)
  | "irde" // Recommendation Context (Phase 4)
  | "uob" // Platform Context (Phase 5 — reserved)
  | "execution" // Execution Context (Phase 6 — reserved)
  | "learning"; // Learning Context (Phase 7 — reserved)

// ── Correlation & Tracing ────────────────────────────────────────────────

/**
 * Correlation identifiers for distributed tracing and replay.
 * A request may carry an inbound correlation id; the Context Manager
 * generates a fresh request id and links the two.
 */
export interface CorrelationIds {
  /** Unique id for THIS cognitive request (generated by Context Manager). */
  requestId: string;
  /** Optional inbound id from the caller (e.g. overlay/screen). */
  correlationId?: string;
  /** Optional session id grouping multiple requests. */
  sessionId?: string;
  /** Optional parent request id (for nested/sub-requests). */
  parentRequestId?: string;
}

// ── Provenance ───────────────────────────────────────────────────────────

/**
 * Provenance entry recorded every time a section is created or enriched.
 * This is the audit trail that makes context explainable and replayable.
 */
export interface ProvenanceEntry {
  /** Which phase/service produced this contribution. */
  source: ContextSectionOwner | string;
  /** ISO-8601 timestamp. */
  timestamp: string;
  /** Context version after this operation. */
  version: number;
  /** What happened. */
  operation: "create" | "enrich" | "validate" | "freeze";
  /** Optional human-readable reason / trigger. */
  reason?: string;
}

// ── Section: Request Context (owner: system) ────────────────────────────

export interface RequestContext {
  /** Original, unmodified user request (text or structured). */
  originalRequest: string;
  /** Normalized request (lowercased, trimmed, language-detected). */
  normalizedRequest: string;
  /** Detected or requested language code (ISO 639-1, e.g. "en", "ar"). */
  language: string;
  /** ISO-8601 timestamp the request was received. */
  receivedAt: string;
  /** Originating surface (chat, voice, search, overlay, api). */
  surface?: string;
  /** Free-form feature tag (e.g. "[travel:recommend]"). */
  featureTag?: string;
}

// ── Section: Session Context (owner: system) ────────────────────────────

export interface SessionContext {
  sessionId: string;
  device?: "mobile" | "desktop" | "tablet" | "api";
  platform?: string;
  locale?: string;
  timezone?: string;
}

// ── Section: Geographic Context (owner: gcie — Phase 1) ─────────────────

export interface GeographicContext {
  location?: { lat: number; lng: number; city?: string; country?: string; neighborhood?: string };
  nearbyEntities?: { type: string; name: string; distance: number }[];
  weather?: { tempC: number; condition: string; icon?: string };
  traffic?: { level: string; delayMin?: number };
  events?: { title: string; date: string; venue: string }[];
  environmentalSignals?: Record<string, unknown>;
}

// ── Section: User Context (owner: pmb — Phase 2) ────────────────────────

export interface UserContext {
  identity?: { username?: string; displayName?: string; verified?: boolean };
  preferences?: string;
  goals?: string[];
  routines?: string[];
  relationships?: { type: string; name: string }[];
  historicalInteractions?: { type: string; count: number; lastAt?: string }[];
  userPermissions?: string[];
  /** Privacy boundary: only fields the user has consented to share. */
  consentScope?: string[];
}

// ── Section: Reasoning Context (owner: crie — Phase 3) ──────────────────

export interface ReasoningContext {
  intent?: string;
  intentType?: string;
  urgency?: "immediate" | "today" | "this_week" | "flexible";
  constraints?: string[];
  clarifications?: string[];
  reasoningGraph?: {
    id: string;
    type: "fact" | "inference" | "goal" | "constraint" | "action" | "question";
    content: string;
    confidence: number;
    sources: string[];
  }[];
  confidence?: number;
  assumptions?: string[];
  decisionType?: string;
}

// ── Section: Validation Context (owner: cross-eval — shared) ────────────

export interface ValidationContext {
  knowledgeGraphValidation?: { hit: boolean; confidence: number };
  aiProviderConsensus?: { providers: string[]; agreement: number };
  webValidation?: { sources: number; freshness: number };
  freshness?: number; // 0-1
  validationConfidence?: number; // 0-1
  discrepancies?: string[];
}

// ── Section: Recommendation Context (owner: irde — Phase 4) ─────────────

export interface RecommendationContext {
  rankedCandidates?: {
    id: string;
    name: string;
    overallScore: number;
    confidence: number;
  }[];
  scores?: Record<string, number>;
  alternatives?: { id: string; name: string }[];
  recommendationRationale?: string;
}

// ── Reserved sections (Phase 5/6/7) ─────────────────────────────────────

/**
 * Platform Context — reserved for Phase 5 (UOB).
 * UOB will populate required modules, dependencies, permissions, execution plan.
 */
export type PlatformContext = Record<string, unknown>;

/**
 * Execution Context — reserved for Phase 6 (Execution Engine).
 */
export type ExecutionContext = Record<string, unknown>;

/**
 * Learning Context — reserved for Phase 7 (Learning Architecture).
 */
export type LearningContext = Record<string, unknown>;

// ── Metadata (owner: system — managed by Context Manager) ───────────────

export interface ContextMetadata {
  /** Schema version (bump when the Shared Context shape changes materially). */
  schemaVersion: number;
  /** Monotonically increasing version within a request lifecycle. */
  version: number;
  /** Correlation ids for tracing. */
  correlation: CorrelationIds;
  /** Full provenance audit trail. */
  provenance: ProvenanceEntry[];
  /** Overall confidence in the context (0-1), derived from section confidences. */
  confidence: number;
  createdAt: string;
  updatedAt: string;
  /** Whether the context has been frozen (read-only terminal state). */
  frozen: boolean;
}

// ── The Shared Context Object ────────────────────────────────────────────

/**
 * The Shared Context Object — the single source of truth that flows through
 * the cognitive pipeline.
 *
 * Ownership map:
 *   metadata      → system (Context Manager)
 *   request       → system
 *   session       → system
 *   geographic    → gcie
 *   user          → pmb
 *   reasoning     → crie
 *   validation    → cross-eval
 *   recommendation→ irde
 *   platform      → uob (reserved)
 *   execution     → execution (reserved)
 *   learning      → learning (reserved)
 *   extensions    → any (future-proof escape hatch)
 */
export interface SharedContext {
  metadata: ContextMetadata;
  request: RequestContext;
  session?: SessionContext;
  geographic?: GeographicContext;
  user?: UserContext;
  reasoning?: ReasoningContext;
  validation?: ValidationContext;
  recommendation?: RecommendationContext;
  platform?: PlatformContext;
  execution?: ExecutionContext;
  learning?: LearningContext;
  /**
   * Escape hatch for future sections without schema changes.
   * Use namespaced keys: `{ "custom.feature.x": ... }`.
   */
  extensions?: Record<string, unknown>;
}

// ── Section identifiers (for typed enrich/validate) ─────────────────────

export type ContextSectionKey =
  | "request"
  | "session"
  | "geographic"
  | "user"
  | "reasoning"
  | "validation"
  | "recommendation"
  | "platform"
  | "execution"
  | "learning";

/**
 * Maps a section key to its constitutional owner. The Context Manager uses
 * this table to enforce ownership on every enrich operation.
 */
export const SECTION_OWNERSHIP: Readonly<Record<ContextSectionKey, ContextSectionOwner>> = Object.freeze({
  request: "system",
  session: "system",
  geographic: "gcie",
  user: "pmb",
  reasoning: "crie",
  validation: "cross-eval",
  recommendation: "irde",
  platform: "uob",
  execution: "execution",
  learning: "learning",
});

// ── Validation ───────────────────────────────────────────────────────────

export interface ContextValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

/**
 * Validate a Shared Context against the schema rules.
 * This is a lightweight structural check — it does NOT reason about content.
 *
 * Rules enforced:
 *   - metadata must exist with version >= 1
 *   - request.originalRequest must be a non-empty string
 *   - every populated section must match its owner's type shape (shallow)
 *   - frozen contexts must not be mutated (caller responsibility; flagged here)
 */
export function validateContext(ctx: SharedContext): ContextValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!ctx.metadata) {
    errors.push("metadata is required");
  } else {
    if (typeof ctx.metadata.version !== "number" || ctx.metadata.version < 1) {
      errors.push("metadata.version must be a positive number");
    }
    if (typeof ctx.metadata.schemaVersion !== "number") {
      errors.push("metadata.schemaVersion is required");
    }
    if (!ctx.metadata.correlation?.requestId) {
      errors.push("metadata.correlation.requestId is required");
    }
    if (!Array.isArray(ctx.metadata.provenance)) {
      errors.push("metadata.provenance must be an array");
    }
  }

  if (!ctx.request) {
    errors.push("request section is required");
  } else {
    if (typeof ctx.request.originalRequest !== "string" || ctx.request.originalRequest.length === 0) {
      errors.push("request.originalRequest must be a non-empty string");
    }
    if (typeof ctx.request.language !== "string") {
      warnings.push("request.language is recommended");
    }
  }

  // Shallow presence checks for owned sections (no deep schema enforcement —
  // phases own their section shapes; the manager only enforces ownership).
  if (ctx.geographic && typeof ctx.geographic !== "object") {
    errors.push("geographic section must be an object");
  }
  if (ctx.user && typeof ctx.user !== "object") {
    errors.push("user section must be an object");
  }
  if (ctx.reasoning && typeof ctx.reasoning !== "object") {
    errors.push("reasoning section must be an object");
  }

  return { valid: errors.length === 0, errors, warnings };
}

// ── Schema version ───────────────────────────────────────────────────────

/**
 * Current Shared Context schema version. Bump this when the shape of
 * SharedContext changes materially. The Context Manager checks compatibility.
 */
export const SHARED_CONTEXT_SCHEMA_VERSION = 1;
